'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace PagoFacilWebService
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://www.miscuotitas.com.ar/PagoFacilWebService", ConfigurationName:="PagoFacilWebService.PagoFacilWebServiceCobranzasSoap")>  _
    Public Interface PagoFacilWebServiceCobranzasSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.miscuotitas.com.ar/PagoFacilWebService/consulta", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function consulta(ByVal sXML As String) As System.Xml.XmlNode
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.miscuotitas.com.ar/PagoFacilWebService/directa", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function directa(ByVal sXML As String) As System.Xml.XmlNode
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.miscuotitas.com.ar/PagoFacilWebService/reversa", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function reversa(ByVal sXML As String) As System.Xml.XmlNode
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface PagoFacilWebServiceCobranzasSoapChannel
        Inherits PagoFacilWebService.PagoFacilWebServiceCobranzasSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class PagoFacilWebServiceCobranzasSoapClient
        Inherits System.ServiceModel.ClientBase(Of PagoFacilWebService.PagoFacilWebServiceCobranzasSoap)
        Implements PagoFacilWebService.PagoFacilWebServiceCobranzasSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function consulta(ByVal sXML As String) As System.Xml.XmlNode Implements PagoFacilWebService.PagoFacilWebServiceCobranzasSoap.consulta
            Return MyBase.Channel.consulta(sXML)
        End Function
        
        Public Function directa(ByVal sXML As String) As System.Xml.XmlNode Implements PagoFacilWebService.PagoFacilWebServiceCobranzasSoap.directa
            Return MyBase.Channel.directa(sXML)
        End Function
        
        Public Function reversa(ByVal sXML As String) As System.Xml.XmlNode Implements PagoFacilWebService.PagoFacilWebServiceCobranzasSoap.reversa
            Return MyBase.Channel.reversa(sXML)
        End Function
    End Class
End Namespace
